### ISSUE TITLE
How to know if region is coast, water or ocean?

### ISSUE THREAD

**Issue by blacksmith94** [redblobgames/mapgen4#5]
Is it possible to know wheter a given region (polygon) is a coast or not, ocean or not and water or not?
I saw this inside the `setMapGeometry` function:
`   
     let coast = r_elevation[r1] < 0.0 || r_elevation[r2] < 0.0;
`
My goal is to create 3 new array properties "r_coast" ,"r_ocean" and "r_water" with booleans. Just like mapgen2 does.
But i don't quite understand it.

**Comment by redblobgames** [comment]
Good questions.

1. mapgen4 doesn't distinguish ocean from lakes. Any time elevation < 0, that's ocean/lake. If you want to distinguish, and if you always have islands, you can run a breadth first search from any point that's on the outer edge of the map. Anything elevation < 0 connected to that point ("connected components") is going to be ocean, and any elevation < 0 that's not connected to the outer edge of the map is a lake. However since the interactive mapgen4 doesn't always generate islands (you can paint whatever you want), there's no way to be sure what's ocean and what's a lake.
2. For coasts, that line of code assigns an *edge* to be coast if one side is land (elevation >= 0) and one side is water (elevation < 0). I think to make r_coast, you can mark any *land* region (elevation >= 0) that has *at least one coastal edge.

**Comment by blacksmith94** [comment]
Yes, that's what i thought.
So assuming I made sure there are no little islands and there is only a single "main" land, then filtered out all the regions with elevation < 0.
How would i get the boundary vertices of the regions?

**Comment by blacksmith94** [comment]
I think i got it working, now I can distinguish between lakes and ocean
Thank you!
![image](https://user-images.githubusercontent.com/19688766/118644852-8233fd00-b7de-11eb-8167-aac869e4ef38.png)
![image](https://user-images.githubusercontent.com/19688766/118644797-77796800-b7de-11eb-95a4-8d8006ef7611.png)

Edit: Now i can also distinguish coasts.
Love your library!
![image](https://user-images.githubusercontent.com/19688766/118662376-3b4f0300-b7f0-11eb-85a3-23c6a2d552ae.png)

**Comment by redblobgames** [comment]
Great!!
