### ISSUE TITLE
Rivers to a tilemap?

### ISSUE THREAD

**Issue by blacksmith94** [redblobgames/mapgen4#6]
I want to translate the generated rivers to a tilemap.
Since I do the polygon rasterization in C#, do i need to do all the math you mention in this article again in order to replicate the rivers? 
https://simblob.blogspot.com/2018/10/mapgen4-river-representation.html
Or is the information stored in the Map object in a way I don't understand?
Any approach on how would you do it?

**Comment by redblobgames** [comment]
The generated rivers are on the triangles, so (like shown in the blog post) each triangle says the next triangle downstream from it, and how much water flows that way.

The data structure is a little bit weird. :-( 

From each triangle `t`, there will be a direction the water flows. The *side* of the triangle where the water flows out is in `t_downslope_s[t]` (this is `s`, an index into the sides array). To find out the next triangle, I think you can use `mesh.s_outer_t(t_downslope_s[t])` to get a triangle index. Then you can draw a line from the start triangle to the next triangle. When `t_downslope_s[t] < 0` that means there is no water flowing out.

If you run mapgen4 and set lg_min_flow to 0, you'll see all of these rivers.

The next thing you might want to do is *not* draw all the rivers. This is what the lg_min_flow parameter does. It looks at how much water is flowing along a side. When `s_flow[t_downslope_s[t]]` is low, that means not much water is flowing there, and you might decide not to draw that river. When `s_flow` is large you will want to draw the river, and if it is very large you might want to draw a wider river. Try adjusting the lg_river_width parameter to see this.

The next thing you might want to do (depending on what your project needs) is draw curves instead of straight lines. This is trickier, and I have a [blog post](https://simblob.blogspot.com/2018/09/mapgen4-river-appearance.html). Instead of drawing a line from triangle to triangle, I draw a curved line inside a triangle, from one side to another side, using the triangle center as the control point.

**Comment by blacksmith94** [comment]
Is it possible to obtain a list of all the parent nodes of the generated rivers?

**Comment by redblobgames** [comment]
More details: both mapgen2 and mapgen4 generate _all_ the downslope directions:

![all downslopes](http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/downslopes.png)

The difference is that in mapgen2 I create some rivers by starting with the mountains and following the flow downwards. In mapgen4 I create _all_ the rivers and creeks and streams. When lg_min_flow is 0, you can see them all:
![mapgen4-generates-all-rivers](https://user-images.githubusercontent.com/8757369/119171740-d37c0080-ba19-11eb-9370-8c514e6caf77.png)

- Mapgen2: calculate all downslopes, calculate some rivers, draw all the rivers
- Mapgen4: calculate all downslopes, calculate all rivers, draw some rivers

The main reason I switched is that I needed to calculate how much water flowed through all the tiny streams and creeks to know how much would flow into the big rivers. I don't want to draw them all because that would be too many, so I only draw the big ones (lg_min_flow slider).

**Comment by blacksmith94** [comment]
Thank you so much!
I think i got it :D
I divided all the rivers into an array of segements with point A and point B and draw straight lines on the grid between those points.
I didn't do the curves part though, if I just increase the number of triangles it just does the trick. But I will probably have to do it when I make the world bigger.

Here are some pictures, still needs a lot of work, this was just the first test in a 1000x1000 grid.
I plan to make a huge world so it will look completely different, but i love the results i got with your library so far.
It's by far the best map generator i've seen.
I will definetely link your website when I start writing a dev-blog, thank you so much Amit.

![image](https://user-images.githubusercontent.com/19688766/119174470-e9fd7880-ba68-11eb-9e77-3348886c02bf.png)
![image](https://user-images.githubusercontent.com/19688766/119174502-f41f7700-ba68-11eb-9dff-4df170341557.png)
![image](https://user-images.githubusercontent.com/19688766/119174578-0994a100-ba69-11eb-9b69-73e106e29126.png)
